
log stderr all;
debug protocols all;
router id 1.1.1.1;

protocol device { }
protocol direct { ipv4; }
protocol kernel { ipv4 { export all; }; }


protocol bgp peer_2 {
    local as 1;
    neighbor 10.99.0.3 as 2;
    ipv4 {
        import all;
        export all;
    };
}
