
log stderr all;
debug protocols all;
router id 2.2.2.2;

protocol device { }
protocol direct { ipv4; }
protocol kernel { ipv4 { export all; }; }


protocol bgp peer_1 {
    local as 2;
    neighbor 10.99.0.2 as 1;
    ipv4 {
        import all;
        export all;
    };
}
